### ISSUE TITLE
allowed_mentions is incorrectly typed and missing new properties

### ISSUE THREAD

**Issue by kgscialdone** [marek12306/corddis#1]
The `allowed_mentions` property on `MessageCreateParamsType` is currently typed as `AllowedMentionsType[]`, which causes a 400 Invalid Form Body error, because only a single value is expected, not an array. It should be typed as `AllowedMentionsType` to fix this.

Additionally, the recent updates adding Reply functionality came with a new property, `replied_user: boolean`, which is currently missing from `AllowedMentionsType`.

The following can be used to manually bypass this issue until fixed: 
```ts
allowed_mentions: { replied_user: false } as unknown as AllowedMentionsType[]
```

**Comment by tfo-dot** [comment]
Thanks for opening an issue about this matter. As of the v0.7.3 version, both problems are solved. Thanks for contributing to the corddis GitHub repository.
